export const objmap = [
    { "default": "Không có thông tin", "key": "iD_Tang_VT", "title": undefined },
    { "default": "Không có thông tin", "key": "ngay_Chay", "title": "Ngày chạy" },
    { "default": "Không có thông tin", "key": "ma_Xe", "title": "Mã xe" },
    { "default": "Không có thông tin", "key": "bien_Xe", "title": undefined },
    { "default": "Không có thông tin", "key": "bien_So_Xe", "title": "Biển số xe" },
    { "default": 0, "key": "trong_Tai", "title": "Trọng tải" },
    { "default": "Không có thông tin", "key": "diem_Di", "title": undefined },
    { "default": "Không có thông tin", "key": "ten_Dia_Diem_DI", "title": "Điểm đi" },
    { "default": "Không có thông tin", "key": "diem_Nhan", "title": undefined },
    { "default": "Không có thông tin", "key": "ten_Dia_Diem_Nhan", "title": "Điểm nhận" },
    { "default": "Không có thông tin", "key": "ma_KH", "title": "Mã khách hàng" },
    { "default": "Không có thông tin", "key": "khach_Hang", "title": undefined },
    { "default": "Không có thông tin", "key": "ten_KH", "title": "Tên khách hàng" },
    { "default": "Không có thông tin", "key": "loai_KH", "title": undefined },
    { "default": "Không có thông tin", "key": "nha_CC", "title": undefined },
    { "default": "Không có thông tin", "key": "ma_Nha_CC", "title": "Mã nhà cung cấp" },
    { "default": "Không có thông tin", "key": "nha_CC_Chot", "title": undefined },
    { "default": "Không có thông tin", "key": "gio_Dat_Xe", "title": undefined },
    { "default": "Không có ghi chú", "key": "ghi_Chu", "title": "Ghi chú" },

    { "default": 0, "key": "cuoc_Thu", "title": "Cước thu" },
    { "default": 0, "key": "cuoc_Tra", "title": "Cước trả" },
    { "default": "Chưa có số seal chi", "key": "so_seal_Chi", "title": "Số seal chi" },
    { "default": "Chưa phê duyệt", "key": "phe_Duyet", "title": "Trạng thái duyệt" },

    { "default": "Không có thông tin", "key": "giao_nop_BB", "title": undefined },
    { "default": "Không có thông tin", "key": "pS_Chi", "title": undefined },
    { "default": "Không có thông tin", "key": "pS_Thu", "title": undefined },
]